services:

  php:
    build:  ./docker/php
    volumes:
      - .:/www

  web:
    image: nginx:1.19
    volumes:
      - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/www/public
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    ports:
      - '80:80'

  db:
    image: mariadb:11.6
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'

  node:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '9000:9000'
