<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250608000001 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            INSERT INTO `skyrim_effect` (`id`, `name_en`, `name_fr`) VALUES
                (1, 'weakness to frost', 'vulnérabilité à la glace'),
                (2, 'fortify sneak', 'renfort de furtivité'),
                (3, 'weakness to poison', 'vulnérabilité au poison'),
                (4, 'fortify restoration', 'renfort de guérison'),
                (5, 'restore stamina', 'restauration de vigueur'),
                (6, 'fortify health', 'renfort de santé'),
                (7, 'fortify one-handed', 'renfort d''arme à une main'),
                (8, 'damage magicka regen', 'dégâts magie récupération'),
                (9, 'ravage stamina', 'vigueur endommagée'),
                (10, 'regenerate stamina', 'récupération de vigueur'),
                (11, 'weakness to shock', 'vulnérabilité à la foudre'),
                (12, 'resist poison', 'résistance au poison'),
                (13, 'fortify light armor', 'renfort d''armure légère'),
                (14, 'fortify destruction', 'renfort de destruction'),
                (15, 'weakness to fire', 'vulnérabilité au feu'),
                (16, 'fortify block', 'renfort de parade'),
                (17, 'resist magic', 'résistance à la magie'),
                (18, 'damage stamina', 'pénalité de vigueur'),
                (19, 'restore health', 'restauration de santé'),
                (20, 'frenzy', 'frénésie'),
                (21, 'fortify smithing', 'renfort de forgeage'),
                (22, 'fortify conjuration', 'renfort de conjuration'),
                (23, 'fortify enchanting', 'renfort d''enchantement'),
                (24, 'resist shock', 'résistance à la foudre'),
                (25, 'fortify pickpocket', 'renfort de vol à la tire'),
                (26, 'fear', 'peur'),
                (27, 'resist fire', 'résistance au feu'),
                (28, 'restore magicka', 'restauration de magie'),
                (29, 'paralysis', 'paralysie'),
                (30, 'fortify magicka', 'renfort de magie'),
                (31, 'lingering damage stamina', 'pénalité de vigueur persistante'),
                (32, 'fortify barter', 'renfort de marchandage'),
                (33, 'damage magicka', 'pénalité de magie'),
                (34, 'fortify marksman', 'renfort de précision'),
                (35, 'cure disease', 'potion médicinale'),
                (36, 'fortify stamina', 'renfort de vigueur'),
                (37, 'invisibility', 'invisibilité'),
                (38, 'waterbreathing', 'respiration aquatique'),
                (39, 'fortify carry weight', 'renfort de portage'),
                (40, 'damage stamina regen', 'dégâts vigueur récupération'),
                (41, 'weakness to magic', 'vulnérabilité à la magie'),
                (42, 'damage health', 'pénalité de santé'),
                (43, 'ravage health', 'santé endommagée'),
                (44, 'slow', 'langueur'),
                (45, 'fortify illusion', 'renfort d''illusion'),
                (46, 'fortify two-handed', 'renfort d''arme à deux mains'),
                (47, 'regenerate magicka', 'regain magique'),
                (48, 'fortify lockpicking', 'renfort de crochetage'),
                (49, 'resist frost', 'résistance à la glace'),
                (50, 'ravage magicka', 'magie endommagée'),
                (51, 'regenerate health', 'régénération de santé'),
                (52, 'fortify alteration', 'renfort d''altération'),
                (53, 'lingering damage magicka', 'pénalité magie persistante'),
                (54, 'fortify heavy armor', 'renfort d''armure lourde'),
                (55, 'lingering damage health', 'pénalité de santé persistante')
            ;
        SQL);
        $this->addSql(<<<'SQL'
            INSERT INTO `skyrim_ingredient` (`id`, `name_en`, `name_fr`) VALUES
                (1, 'Abecean Longfin', 'Abécéen à Longue Nageoire'),
                (2, 'Bear Claws', 'Griffe d''Ours'),
                (3, 'Bee', 'Abeille'),
                (4, 'Beehive Husk', 'Ruche Vide'),
                (5, 'Bleeding Crown', 'Couronne Sanglante'),
                (6, 'Blisterwort', 'Cloquerille'),
                (7, 'Blue Butterfly Wing', 'Aile de Papillon Bleu'),
                (8, 'Blue Dartwing', 'Aile de Fléchette Bleue'),
                (9, 'Blue Mountain Flower', 'Lys des Cimes Bleu'),
                (10, 'Bone Meal', 'Farine d''Os'),
                (11, 'Briar Heart', 'Coeur de Ronce'),
                (12, 'Butterfly Wing', 'Aile de Papillon'),
                (13, 'Canis Root', 'Racine de Canis'),
                (14, 'Charred Skeever Hide', 'Peau de Ragnard Carbonisé'),
                (15, 'Chaurus Eggs', 'Oeuf de Chaurus'),
                (16, 'Chicken''s Egg', 'Oeuf de Poule'),
                (17, 'Creep Cluster', 'Plante Grimpante'),
                (18, 'Crimson Nirnroot', 'Nirnroot Cramoisie'),
                (19, 'Cyrodilic Spadetail', 'Poisson Combattant de Cyrodiil'),
                (20, 'Daedra Heart', 'Coeur de Daedra'),
                (21, 'Deathbell', 'Grelot-de-la-mort'),
                (22, 'Dragon''s Tongue', 'Langue de Dragon'),
                (23, 'Dwarven Oil', 'Huile Dwemer'),
                (24, 'Ectoplasm', 'Ectoplasme'),
                (25, 'Elves Ear', 'Oreille d''Elfe'),
                (26, 'Eye of Sabre Cat', 'Oeil de Smilodon'),
                (27, 'Falmer Ear', 'Oreille de Falmer'),
                (28, 'Fire Salts', 'Sels de Feu'),
                (29, 'Fly Amanita', 'Amanite Tue-mouches'),
                (30, 'Frost Mirriam', 'Hivernelle'),
                (31, 'Frost Salts', 'Sels de Givre'),
                (32, 'Garlic', 'Ail'),
                (33, 'Giant Lichen', 'Lichen Géant'),
                (34, 'Giant''s Toe', 'Orteil de Géant'),
                (35, 'Glow Dust', 'Poussière Luisante'),
                (36, 'Glowing Mushroom', 'Champignon luisant'),
                (37, 'Grass Pod', 'Cosse'),
                (38, 'Hagraven Claw', 'Serre d''Harfreuse'),
                (39, 'Hagraven Feathers', 'Plume d''Harfreuse'),
                (40, 'Hanging Moss', 'Mousse Barbue'),
                (41, 'Hawk Beak', 'Bec de Faucon'),
                (42, 'Hawk Feathers', 'Plume de Faucon'),
                (43, 'Histcarp', 'Carpe du Hist'),
                (44, 'Honeycomb', 'Rayon de Miel'),
                (45, 'Human Flesh', 'Chair Humaine'),
                (46, 'Human Heart', 'Coeur Humain'),
                (47, 'Ice Wraith Teeth', 'Dent de Spectre de Glace'),
                (48, 'Imp Stool', 'Pied-de-lutin'),
                (49, 'Jazbay Grapes', 'Raisin Jazbay'),
                (50, 'Juniper Berries', 'Genièvre'),
                (51, 'Large Antlers', 'Grande Ramure'),
                (52, 'Lavender', 'Lavande'),
                (53, 'Luna Moth Wing', 'Aile de Noctuelle'),
                (54, 'Moon Sugar', 'Sucrelune'),
                (55, 'Mora Tapinella', 'Mora Topinella'),
                (56, 'Mudcrab Chitin', 'Chitine de Vasard'),
                (57, 'Niamira''s Rot', 'Truffe de Namira'),
                (58, 'Nightshade', 'Obscurcine'),
                (59, 'Nirnroot', 'Nirnroot'),
                (60, 'Nordic Barnacle', 'Bernache nordique'),
                (61, 'Orange Dartwing', 'Aile de Fléchette Orange'),
                (62, 'Pearl', 'Perle'),
                (63, 'Pine Thrush Egg', 'Oeuf de Grive'),
                (64, 'Powdered Mammoth Tusk', 'Défense de Mammouth en Poudre'),
                (65, 'Purple Mountain Flower', 'Lys des Cimes Violet'),
                (66, 'Red Mountain Flower', 'Lys des Cimes Rouge'),
                (67, 'River Betty', 'Poisson de Rivière'),
                (68, 'Rock Warbler Egg', 'Oeuf de Fauvette'),
                (69, 'Sabre Cat Tooth', 'Dent de Smilodon'),
                (70, 'Salt Pile', 'Tas de Sel'),
                (71, 'Scaly Pholiata', 'Pholiote à Écaille'),
                (72, 'Silverside Perch', 'Perche Argentée'),
                (73, 'Skeever Tail', 'Queue de Ragnard'),
                (74, 'Slaughterfish Egg', 'Oeuf de Poisson Carnassier'),
                (75, 'Slaughterfish Scales', 'Écaille de Poisson Carnassier'),
                (76, 'Small Antlers', 'Petite Ramure'),
                (77, 'Small Pearl', 'Petite Perle'),
                (78, 'Snowberries', 'Givreboise'),
                (79, 'Spider Egg', 'Oeuf d''Araignée'),
                (80, 'Spriggan Sap', 'Sève de Spriggan'),
                (81, 'Swamp Fungal Pod', 'Mycène des Marais'),
                (82, 'Taproot', 'Racine Noueuse'),
                (83, 'Thistle Branch', 'Tige de Chardon'),
                (84, 'Torchbug Thorax', 'Thorax de Flammouche'),
                (85, 'Troll Fat', 'Graisse de Troll'),
                (86, 'Tundra Cotton', 'Coton Sauvage'),
                (87, 'Vampire Dust', 'Poussière de Vampire'),
                (88, 'Void Salts', 'Sels du Néant'),
                (89, 'Wheat', 'Blé'),
                (90, 'White Cap', 'Chapeau Blanc'),
                (91, 'Wisp Wrappings', 'Voiles Éthérés')
            ;
        SQL);
        $this->addSql(<<<'SQL'
            INSERT INTO `skyrim_ingredient_effect` (`ingredient_id`, `effect_id`) VALUES
               (1, 1),
               (1, 2),
               (1, 3),
               (1, 4),
               (2, 5),
               (2, 6),
               (2, 7),
               (2, 8),
               (3, 5),
               (3, 9),
               (3, 10),
               (3, 11),
               (4, 12),
               (4, 13),
               (4, 2),
               (4, 14),
               (5, 15),
               (5, 16),
               (5, 3),
               (5, 17),
               (6, 18),
               (6, 19),
               (6, 20),
               (6, 21),
               (7, 18),
               (7, 8),
               (7, 22),
               (7, 23),
               (8, 24),
               (8, 19),
               (8, 25),
               (8, 26),
               (9, 19),
               (9, 22),
               (9, 6),
               (9, 8),
               (10, 18),
               (10, 22),
               (10, 27),
               (10, 9),
               (11, 28),
               (11, 16),
               (11, 29),
               (11, 30),
               (12, 19),
               (12, 31),
               (12, 32),
               (12, 33),
               (13, 18),
               (13, 34),
               (13, 7),
               (13, 29),
               (14, 5),
               (14, 12),
               (14, 35),
               (14, 19),
               (15, 3),
               (15, 36),
               (15, 33),
               (15, 37),
               (16, 17),
               (16, 38),
               (16, 8),
               (16, 31),
               (17, 28),
               (17, 39),
               (17, 40),
               (17, 41),
               (18, 42),
               (18, 37),
               (18, 18),
               (18, 17),
               (19, 18),
               (19, 26),
               (19, 4),
               (19, 43),
               (20, 40),
               (20, 33),
               (20, 19),
               (20, 26),
               (21, 42),
               (21, 9),
               (21, 44),
               (21, 3),
               (22, 27),
               (22, 32),
               (22, 45),
               (22, 46),
               (23, 41),
               (23, 47),
               (23, 45),
               (23, 28),
               (24, 28),
               (24, 14),
               (24, 30),
               (24, 42),
               (25, 28),
               (25, 1),
               (25, 34),
               (25, 27),
               (26, 5),
               (26, 33),
               (26, 43),
               (26, 19),
               (27, 42),
               (27, 20),
               (27, 12),
               (27, 48),
               (28, 1),
               (28, 28),
               (28, 27),
               (28, 47),
               (29, 27),
               (29, 20),
               (29, 46),
               (29, 10),
               (30, 49),
               (30, 2),
               (30, 50),
               (30, 40),
               (31, 15),
               (31, 49),
               (31, 28),
               (31, 22),
               (32, 12),
               (32, 36),
               (32, 47),
               (32, 51),
               (33, 43),
               (33, 3),
               (33, 11),
               (33, 28),
               (34, 18),
               (34, 39),
               (34, 6),
               (34, 40),
               (35, 33),
               (35, 14),
               (35, 8),
               (35, 24),
               (36, 24),
               (36, 14),
               (36, 21),
               (36, 6),
               (37, 12),
               (37, 50),
               (37, 52),
               (37, 28),
               (38, 17),
               (38, 53),
               (38, 23),
               (38, 32),
               (39, 33),
               (39, 20),
               (39, 22),
               (39, 11),
               (40, 33),
               (40, 8),
               (40, 6),
               (40, 7),
               (41, 5),
               (41, 49),
               (41, 39),
               (41, 24),
               (42, 35),
               (42, 13),
               (42, 7),
               (42, 2),
               (43, 5),
               (43, 30),
               (43, 40),
               (43, 38),
               (44, 5),
               (44, 16),
               (44, 13),
               (44, 9),
               (45, 42),
               (45, 29),
               (45, 28),
               (45, 2),
               (46, 42),
               (46, 8),
               (46, 33),
               (46, 20),
               (47, 1),
               (47, 54),
               (47, 37),
               (47, 15),
               (48, 42),
               (48, 29),
               (48, 55),
               (48, 19),
               (49, 41),
               (49, 30),
               (49, 47),
               (49, 43),
               (50, 15),
               (50, 51),
               (50, 34),
               (50, 40),
               (51, 5),
               (51, 36),
               (51, 44),
               (51, 40),
               (52, 17),
               (52, 36),
               (52, 50),
               (52, 22),
               (53, 33),
               (53, 13),
               (53, 51),
               (53, 37),
               (54, 15),
               (54, 49),
               (54, 28),
               (54, 47),
               (55, 28),
               (55, 55),
               (55, 10),
               (55, 45),
               (56, 5),
               (56, 35),
               (56, 12),
               (56, 27),
               (57, 33),
               (57, 26),
               (57, 48),
               (57, 51),
               (58, 42),
               (58, 8),
               (58, 31),
               (58, 14),
               (59, 42),
               (59, 18),
               (59, 37),
               (59, 17),
               (60, 33),
               (60, 38),
               (60, 51),
               (60, 25),
               (61, 5),
               (61, 50),
               (61, 25),
               (61, 55),
               (62, 5),
               (62, 28),
               (62, 16),
               (62, 24),
               (63, 5),
               (63, 48),
               (63, 3),
               (63, 24),
               (64, 5),
               (64, 15),
               (64, 2),
               (64, 26),
               (65, 5),
               (65, 2),
               (65, 53),
               (65, 49),
               (66, 28),
               (66, 50),
               (66, 30),
               (66, 42),
               (67, 42),
               (67, 52),
               (67, 44),
               (67, 39),
               (68, 19),
               (68, 7),
               (68, 18),
               (68, 41),
               (69, 5),
               (69, 54),
               (69, 21),
               (69, 3),
               (70, 41),
               (70, 4),
               (70, 44),
               (70, 47),
               (71, 41),
               (71, 45),
               (71, 10),
               (71, 39),
               (72, 5),
               (72, 40),
               (72, 43),
               (72, 49),
               (73, 40),
               (73, 43),
               (73, 42),
               (73, 13),
               (74, 12),
               (74, 25),
               (74, 55),
               (74, 36),
               (75, 49),
               (75, 55),
               (75, 54),
               (75, 16),
               (76, 3),
               (76, 4),
               (76, 31),
               (76, 42),
               (77, 5),
               (77, 7),
               (77, 4),
               (77, 49),
               (78, 27),
               (78, 23),
               (78, 49),
               (78, 24),
               (79, 18),
               (79, 8),
               (79, 48),
               (79, 34),
               (80, 8),
               (80, 23),
               (80, 21),
               (80, 52),
               (81, 24),
               (81, 53),
               (81, 29),
               (81, 19),
               (82, 41),
               (82, 45),
               (82, 47),
               (82, 28),
               (83, 49),
               (83, 9),
               (83, 12),
               (83, 54),
               (84, 5),
               (84, 53),
               (84, 41),
               (84, 36),
               (85, 12),
               (85, 46),
               (85, 20),
               (85, 42),
               (86, 17),
               (86, 30),
               (86, 16),
               (86, 32),
               (87, 37),
               (87, 51),
               (87, 28),
               (87, 35),
               (88, 11),
               (88, 17),
               (88, 42),
               (88, 30),
               (89, 19),
               (89, 6),
               (89, 40),
               (89, 53),
               (90, 1),
               (90, 54),
               (90, 28),
               (90, 50),
               (91, 5),
               (91, 14),
               (91, 39),
               (91, 17)
            ;
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            DELETE FROM skyrim_ingredient_effect WHERE 1;
            DELETE FROM skyrim_effect WHERE 1;
            DELETE FROM skyrim_ingredient WHERE 1;
        SQL);
    }
}
